Repository HarshCasper/Rotten-Scripts, pull requests merged in 2020-12, with the labels that each got.

#432 Python Script to bomb issues on a Repository (Issue #384)
  Python/Github_Bomb_Issues/README.md
  Python/Github_Bomb_Issues/Snippets/how-to.png
  Python/Github_Bomb_Issues/bomb-issues.py
  Python/Github_Bomb_Issues/requirements.txt
Labels: hacktoberfest-accepted

#418 Added Discord_Bot
  Python/Discord_bot/README.md
  Python/Discord_bot/image.jpg
  Python/Discord_bot/main.py
  Python/Discord_bot/package.json
  Python/Discord_bot/requirements.txt
Labels: hacktoberfest-accepted

#477 created a rot13 folder
  JavaScript/ROT13/README.md
  JavaScript/ROT13/rot13.js
  Python/ROT13/README.md
  Python/ROT13/ROT13.py
Labels: hacktoberfest-accepted

#618 A new script to get rank wise google search links added
  Python/Query_Links_Script/Readme.MD
  Python/Query_Links_Script/query_script.py
  Python/Query_Links_Script/requirements.txt
Labels: Don't Merge Yet, Work-In-Progress

#615 Cryptocurrency Converter Script
  Python/cryptocurrency_converter/README.md
  Python/cryptocurrency_converter/crypto_converter.py
Labels: Don't Merge Yet, Work-In-Progress

#611 Merge two PDF Script
  Python/mergetwopdf/MergedFiles.pdf
  Python/mergetwopdf/Readme.MD
  Python/mergetwopdf/merge.py
Labels: Don't Merge Yet, no-updates
