Repository HarshCasper/Rotten-Scripts, pull requests merged in 2021-01, with the labels that each got.

#607 Send E-Mails through the G-Mail REST API via OAuth 2.0
  Python/Send_Email_Using_Gmail_Api/README.md
  Python/Send_Email_Using_Gmail_Api/auth.py
  Python/Send_Email_Using_Gmail_Api/console.png
  Python/Send_Email_Using_Gmail_Api/credentials.json
  Python/Send_Email_Using_Gmail_Api/requirement.txt
  Python/Send_Email_Using_Gmail_Api/script.py
  Python/Send_Email_Using_Gmail_Api/terminal.gif
Labels: Don't Merge Yet, Work-In-Progress

#657 Added Text Extraction from Images
  Python/Text_Extract/README.md
  Python/Text_Extract/img/Output.PNG
  Python/Text_Extract/img/Sample.PNG
  Python/Text_Extract/img/TextFile.PNG
  Python/Text_Extract/requirements.txt
  Python/Text_Extract/text_extract.py
Labels: Under-Review

#687 Added Bash Script for hunting a username on various social channels and displaying the output
  Bash/Hunt_Username/README.md
  Bash/Hunt_Username/huntUsername.sh
Labels: Under-Review, Work-In-Progress

#709 Add powershell custom prompt Script
  PowerShell/Custom_Prompt/README.md
  PowerShell/Custom_Prompt/profile.ps1
Labels: Under-Review

#702 Music Genre Classification
  Python/Music_Genre_Classification/Features/GTZAN.csv
  Python/Music_Genre_Classification/README.md
  Python/Music_Genre_Classification/feature_extraction.py
  Python/Music_Genre_Classification/genre_classification.py
  Python/Music_Genre_Classification/requirements.txt
Labels: Under-Review
