Repository HarshCasper/Rotten-Scripts, pull requests merged in 2021-04, with the labels that each got.

#936 Verbose mode added and Improve output formatting #923
  Python/PR_Workflow/README.md
  Python/PR_Workflow/prw.py
  Python/PR_Workflow/src/drivefunc.py
  Python/PR_Workflow/src/extracktor.py
  Python/PR_Workflow/src/graphqlapi.py
Labels: GSSOC21, Level2, PR:Ready-to-Merge

#939 Add script to auto update readme by recent hashnode blogs
  JavaScript/Update_README_With_Hashnode_Blogs/DemoREADME.md
  JavaScript/Update_README_With_Hashnode_Blogs/README.md
  JavaScript/Update_README_With_Hashnode_Blogs/recent_blogs.yml
  JavaScript/Update_README_With_Hashnode_Blogs/update_readme.js
Labels: GSSOC21, Level3, PR:Ready-to-Merge

#941 #821 Background subtractor files added
  Python/Background_Subtractor/BG_Subtractor.py
  Python/Background_Subtractor/README.md
  Python/Background_Subtractor/requirements.txt
Labels: GSSOC21, PR:Ready-to-Merge, PR:Reviewed

#940 Script-addition : Twitter unfollower js
  .gitignore
  JavaScript/Twitter_Unfollowers/README.md
  JavaScript/Twitter_Unfollowers/Twitter_Unfollowers.js
  JavaScript/Twitter_Unfollowers/apiTokens.js
  JavaScript/Twitter_Unfollowers/dbFunc.js
  JavaScript/Twitter_Unfollowers/package-lock.json
  JavaScript/Twitter_Unfollowers/package.json
  JavaScript/Twitter_Unfollowers/twitterFunc.js
Labels: GSSOC21, PR:Under-Review

#938 PR_for_BTCtracker_golang
  Go/Bitcoin_Price_Tracker/Readme.md
  Go/Bitcoin_Price_Tracker/go.mod
  Go/Bitcoin_Price_Tracker/go.sum
  Go/Bitcoin_Price_Tracker/main.go
Labels: GSSOC21, PR:Reviewed

#949 Script to fetch all Issues/PRs and store them in a CSV/JSON File #932
  Python/Github_Issues_PRs_Scrapper/.env.example
  Python/Github_Issues_PRs_Scrapper/README.md
  Python/Github_Issues_PRs_Scrapper/master_fetch_script.py
  Python/Github_Issues_PRs_Scrapper/requirements.txt
Labels: GSSOC21, Level3, PR:Under-Review

#945 Added Active_pull_request_commentors
  JavaScript/Active_pull_request_commentors/.env_example
  JavaScript/Active_pull_request_commentors/package-lock.json
  JavaScript/Active_pull_request_commentors/package.json
  JavaScript/Active_pull_request_commentors/readme.md
  JavaScript/Active_pull_request_commentors/script.js
Labels: GSSOC21, Level3

#918 CamScanner Script
  Python/Camscanner/README.md
  Python/Camscanner/camscanner.py
  Python/Camscanner/requirements.txt
Labels: GSSOC21, PR:Ready-to-Merge, bug, question

#896 Added Gmeet py bot
  Python/Gmeet_Bot/.env.example
  Python/Gmeet_Bot/Gmeet_buddy.py
  Python/Gmeet_Bot/Readme.md
Labels: GSSOC21, PR:Ready-to-Merge, PR:Reviewed

#1009 #943 Domain Name Availability
  Python/Domain_Name_Availability/.env.example
  Python/Domain_Name_Availability/Domain_name.py
  Python/Domain_Name_Availability/README.md
  Python/Domain_Name_Availability/requirements.txt
Labels: GSSOC21, PR:Ready-to-Merge

#984 Command line based Pomodoro Timer
  Python/Pomodoro_Timer/Pomodoro.py
  Python/Pomodoro_Timer/README.md
  Python/Pomodoro_Timer/block_urls.txt
Labels: GSSOC21, Level3, PR:Ready-to-Merge

#1012 FeatureNotFound bug corrected
  Python/Email_Scrape_From_Webpage/webpage-email-scrape.py
Labels: GSSOC21, Level1

#971 Sift algorithm
  Python/SIFT Algorithm/Readme.md
  Python/SIFT Algorithm/SIFT_Algorithm.py
Labels: GSSOC21, Level3

#950 Added Issue Fetch Details
  JavaScript/Github_Fetch_Issue_Details/README.md
  JavaScript/Github_Fetch_Issue_Details/issueDetails.js
  JavaScript/Github_Fetch_Issue_Details/issueDetails.json
  JavaScript/Github_Fetch_Issue_Details/package-lock.json
  JavaScript/Github_Fetch_Issue_Details/package.json
Labels: GSSOC21, Level3, PR:Ready-to-Merge

#916 Added Amazon price tracker
  JavaScript/Amazon_Price_Tracker/ReadMe.md
  JavaScript/Amazon_Price_Tracker/index.js
  JavaScript/Amazon_Price_Tracker/package-lock.json
  JavaScript/Amazon_Price_Tracker/package.json
  package-lock.json
Labels: GSSOC21, PR:Ready-to-Merge, question
