Repository HarshCasper/Rotten-Scripts, pull requests merged in 2021-03, with the labels that each got.

#814 Make linguist ignore *.ipynb files
  .gitattributes
Labels: GSSoC'21, Level0, PR:Ready-to-Merge, PR:Reviewed

#829 Changed CONTRIBUTING.md
  CONTRIBUTING.md
Labels: GSSoC'21, Level0, PR:Ready-to-Merge

#827 added maintiners in place of project admin
  README.md
Labels: PR:Ready-to-Merge, PR:Reviewed

#840 Added GSSOC in Open_Source_Events
  Open_Source_Events/GSSOC/README.md
  Open_Source_Events/README.md
Labels: GSSOC21, Level0, PR:Ready-to-Merge

#835 Added-Movie-Info-Telegram-Bot in Python
  Python/Movie-Info-Telegram-Bot/.env.example
  Python/Movie-Info-Telegram-Bot/README.md
  Python/Movie-Info-Telegram-Bot/bot.py
  Python/Movie-Info-Telegram-Bot/requirements.txt
Labels: GSSOC21, Level3, PR:Ready-to-Merge

#852 Adding files for #579
  Python/Twitter_Hashtags/Hashtag_Scrape.py
  Python/Twitter_Hashtags/README.md
Labels: GSSOC21, PR:Ready-to-Merge

#851 Added Coderforces Scraping files to Codeforces_Scraper
  Python/Coderforces_Problem_Scrapper/Codeforces_problem_scrapper.py
  Python/Coderforces_Problem_Scrapper/README.md
  Python/Coderforces_Problem_Scrapper/requirements.txt
Labels: GSSOC21, Level3

#850 chore(pylint) : Ignore module doc string from pylint
  .github/linters/.python-lint.yml
Labels: GSSOC21, Level0, PR:Ready-to-Merge, PR:Reviewed

#839 Add Khan Academy Downloader bash script
  Bash/KhanAcademy_Downloader/README.md
  Bash/KhanAcademy_Downloader/khanacademy-dl.sh
Labels: GSSOC21

#845 Update and Add functionalities to the old CLI ver. of Cryptocurrency Converter (Fixed and Refactored.)
  Python/Cryptocurrency_Converter/crypto_converter.py
Labels: GSSOC21, PR:Ready-to-Merge, PR:Reviewed

#859 Add Scrap Latest Torrents
  Python/Scrap_Latest_Torrents/README.md
  Python/Scrap_Latest_Torrents/requirements.txt
  Python/Scrap_Latest_Torrents/scrap_latest_torrents.py
Labels: PR:Ready-to-Merge

#877 Updated get_lyrics.py to accept strings with spaces and Uppercase
  Python/Get_Lyrics/get_lyrics.py
Labels: GSSOC21, Level2, PR:Ready-to-Merge

#795 Added Distance Calculator App
  Python/Distance_Calculator_App/README.md
  Python/Distance_Calculator_App/main.py
  Python/Distance_Calculator_App/requirements.txt
Labels: GSSOC21, Level2, PR:Ready-to-Merge, PR:Reviewed

#894 add all files of pr workflow #756
  Python/PR_Workflow/README.md
  Python/PR_Workflow/config.ini
  Python/PR_Workflow/prw.py
  Python/PR_Workflow/requirements.txt
  Python/PR_Workflow/src/extracktor.py
  Python/PR_Workflow/src/graphqlapi.py
  Python/PR_Workflow/src/prapi.py
Labels: GSSOC21, PR:Reviewed

#887 Footballer club info wikipedia scraper for issue #466
  Python/Wikipedia_Footballer_Scraper/README.md
  Python/Wikipedia_Footballer_Scraper/main.py
  Python/Wikipedia_Footballer_Scraper/requirements.txt
Labels: GSSOC21, PR:Ready-to-Merge, PR:Reviewed

#777 Anime tracker in python
  Python/Anime-tracker/README.md
  Python/Anime-tracker/requirements.txt
  Python/Anime-tracker/tracker.py
Labels: PR:Ready-to-Merge, PR:Reviewed

#898 Delete tweets
  Python/Delete_Tweets/README.md
  Python/Delete_Tweets/credentials.json
  Python/Delete_Tweets/helper.py
  Python/Delete_Tweets/main.py
  Python/Delete_Tweets/requirements.txt
Labels: GSSOC21, Level3, PR:Ready-to-Merge

#776 STL Viewer and Combiner
  Python/README.md
  Python/View_and_Combine_STL/README.md
  Python/View_and_Combine_STL/combine.py
  Python/View_and_Combine_STL/requirements.txt
  Python/View_and_Combine_STL/view.py
Labels: PR:No-Updates, PR:Ready-to-Merge, PR:Reviewed

#844 JavaScript Readme under #issue-826
  JavaScript/README.md
Labels: Level1, PR:Reviewed, PR:Under-Review

#854 new python README
  Python/README.md
Labels: GSSOC21, PR:Under-Review

#855 RSA script added with README
  Python/RSA_Key_Generation/README.md
  Python/RSA_Key_Generation/RSA.py
  Python/RSA_Key_Generation/keyPair_generation.py
  Python/RSA_Key_Generation/key_pair_generation.py
  Python/RSA_Key_Generation/nature.jpeg
  Python/RSA_Key_Generation/utilities.py
Labels: GSSOC21, PR:Under-Review

#878 Added Linkedin_Scrapper Script
  Python/Linkedin_Connection_Scrapper/Readme.md
  Python/Linkedin_Connection_Scrapper/credentials.json
  Python/Linkedin_Connection_Scrapper/main.py
Labels: GSSOC21, PR:Under-Review

#848 New aws ec2 python script
  Python/Aws_EC2/.env.example
  Python/Aws_EC2/README.md
  Python/Aws_EC2/create_ec2_instance.py
Labels: GSSOC21, PR:Ready-to-Merge, PR:Reviewed

#772 Watermark images
  Python/Watermark_Images/README.md
  Python/Watermark_Images/requirements.txt
  Python/Watermark_Images/watermark_logo.py
  Python/Watermark_Images/watermark_text.py
Labels: PR:Under-Review, Work-In-Progress

#873 Added Bitcoin mining Script
  Python/BitCoin Mining/BitCoin_Mining.py
  Python/BitCoin Mining/README.md
Labels: GSSOC21, PR:Reviewed
