Repository HarshCasper/Rotten-Scripts, pull requests merged in 2021-02, with the labels that each got.

#704 [Bash] Empty Subtitles
  Bash/Multiplexing/Empty-Subtitles/README.md
  Bash/Multiplexing/Empty-Subtitles/emptysubs.sh
Labels: Under-Review

#708 No Subtitles Matroska
  Bash/Multiplexing/No_Subtitles_MKV/README.md
  Bash/Multiplexing/No_Subtitles_MKV/nosubsmkv.sh
Labels: Under-Review

#721 Network scanner
  Python/Network_scanner/network_scanner.py
  Python/Network_scanner/readme.md
Labels: Under-Review

#717 Changed PyLint Action
  .github/linters/.python-lint.yml
  .github/workflows/py_lint.yml
  .github/workflows/pylint.yaml
  .pylintrc
  pyLint.py
Labels: Under-Review

#724 chrome dino game automation in python
  Python/README.md
  Python/chromedino_script/README.md
  Python/chromedino_script/coordinates.py
  Python/chromedino_script/demo_dinogame.gif
  Python/chromedino_script/enemy_location_checker.py
  Python/chromedino_script/main.py
  Python/chromedino_script/requirements.txt
Labels: Under-Review

#782 Twitter scrapper
  Python/Twitter_Scrapper/.env.example
  Python/Twitter_Scrapper/README.md
  Python/Twitter_Scrapper/requirements.txt
  Python/Twitter_Scrapper/twitter_scrapper.py
Labels: Under-Review, Work-In-Progress

#787 Subreddit image scrapper
  Python/Subreddit_Image_Scrapper/README.md
  Python/Subreddit_Image_Scrapper/script.py
Labels: MWoC, Under-Review, Work-In-Progress

#797 Quantum computing script updates
  Python/CONTRIBUTION-GUIDELINE.md
  Python/Quantum_random/.env.example
  Python/Quantum_random/README.md
  Python/Quantum_random/quant_random.py
Labels: Reviewed
