Repository HarshCasper/Rotten-Scripts, pull requests merged in 2021-07, with the labels that each got.

#1174 added linkedin-learning-videos-downloader
  Python/Linkedin_Learning_Video_Downloader/.sample.env
  Python/Linkedin_Learning_Video_Downloader/README.md
  Python/Linkedin_Learning_Video_Downloader/requirements.txt
  Python/Linkedin_Learning_Video_Downloader/script.py
Labels: PR:Ready-to-Review

#1178 Fix Grammatical mistakes and typos found in STYLE_GUIDELINES.md
  STYLE_GUIDELINES.md
Labels: PR:Ready-to-Review

#1124 Linkedin Wish Sender
  Python/Linkedin_Wishes_Sender/.sample.env
  Python/Linkedin_Wishes_Sender/Readme.md
  Python/Linkedin_Wishes_Sender/requirements.txt
  Python/Linkedin_Wishes_Sender/script.py
  Python/README.md
Labels: PR:Ready-to-Review, PR:Reviewed

#1182 greeting bot correction
  .github/workflows/greeting.yml
  .github/workflows/greetings.yml
Labels: PR:Ready-to-Review

#1185 added pdf2videoconvertr
  Python/Pdf2videoConverter/Readme.md
  Python/Pdf2videoConverter/requirements.txt
  Python/Pdf2videoConverter/script.py
Labels: PR:Ready-to-Review

#1160 'how to' type qus using voice
  Python/Ask_How_To_Qus_using_Voice/README.md
  Python/Ask_How_To_Qus_using_Voice/how_to.py
  Python/Ask_How_To_Qus_using_Voice/requirements.txt
Labels: LGM-SOC, PR:Ready-to-Review, PR:Reviewed

#1175 Fetch Contributions python script
  Python/Fetch_Contributions/README.md
  Python/Fetch_Contributions/fetch_contributions.py
  Python/Fetch_Contributions/requirements.txt
Labels: PR:Ready-to-Review, PR:Reviewed

#1190 feat: add twitter image downloading script
  Python/Twitter_Images_Downloader/.env.example
  Python/Twitter_Images_Downloader/README.md
  Python/Twitter_Images_Downloader/images_download.py
  Python/Twitter_Images_Downloader/requirements.txt
Labels: PR:Ready-to-Review
