Repository HarshCasper/Rotten-Scripts, pull requests merged in 2021-05, with the labels that each got.

#1029 Youtube video downloader in rust
  .gitignore
  Rust/Youtube_Downloader/Cargo.lock
  Rust/Youtube_Downloader/Cargo.toml
  Rust/Youtube_Downloader/README.md
  Rust/Youtube_Downloader/src/cli.rs
  Rust/Youtube_Downloader/src/main.rs
Labels: GSSOC21, Level3, PR:Ready-to-Merge

#868 adding network passwords
  Python/Network_passwords/.env.example
  Python/Network_passwords/README.md
  Python/Network_passwords/script.py
Labels: GSSOC21, PR:Under-Review

#902 Add Color_picker
  Python/Color_Picker/Color_Picker.py
  Python/Color_Picker/README.md
  Python/Color_Picker/colors.csv
  Python/Color_Picker/requirement.txt
Labels: PR:Under-Review

#903 Issue 444: Added Test Data Generator Code & modified README files
  Python/Test_Data_Generator/README.md
  Python/Test_Data_Generator/Test data generator.ipynb
  Python/Test_Data_Generator/Test data generator.py
Labels: GSSOC21, PR:Under-Review

#1040 added action for greeting to all
  .github/workflows/greeting.yml
Labels: GSSOC21, Level3
