Repository HarshCasper/Rotten-Scripts, pull requests merged in 2021-08, with the labels that each got.

#1156 Video to pdf (CLI)
  Python/Video to PDF(CLI)/README.md
  Python/Video to PDF(CLI)/requirements.txt
  Python/Video to PDF(CLI)/video_to_pdf.py
Labels: LGM-SOC, PR:Ready-to-Review, PR:Reviewed

#1202 Issue forms (#1201)
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/script_request.md
  .github/ISSUE_TEMPLATE/script_request.yml
Labels: PR:No-Issue

#1184 added facebook request accepter
  Python/Fb_Request_Accepter/.sample.env
  Python/Fb_Request_Accepter/README.md
  Python/Fb_Request_Accepter/requirements.txt
  Python/Fb_Request_Accepter/script.py
  Python/README.md
Labels: PR:Reviewed, PR:Ready-to-Review

#1177 Script to collect Spam /Invalid PR across the GitHub Repo
  Python/Git_Repo_Spam_Aggregator/README.md
  Python/Git_Repo_Spam_Aggregator/get_spam_Invalid_pr.py
  Python/Git_Repo_Spam_Aggregator/repositories.json
  Python/Git_Repo_Spam_Aggregator/requirements.txt
  Python/README.md
Labels: PR:Reviewed, PR:Ready-to-Review

#1207 twitter-giveway script
  Python/Twitter_Giveaway/.sample.env
  Python/Twitter_Giveaway/Readme.md
  Python/Twitter_Giveaway/requirements.txt
  Python/Twitter_Giveaway/script.py
Labels: PR:Ready-to-Review

#1230 Add a machine learning based news scrapper
  Python/machine-learning-news-scrapper/README.md
  Python/machine-learning-news-scrapper/machine_learning_news_scrapper.py
  Python/machine-learning-news-scrapper/models/cv.pkl
  Python/machine-learning-news-scrapper/models/mnb.pkl
  Python/machine-learning-news-scrapper/models/mnb_clf_joblib
  Python/machine-learning-news-scrapper/models/mnb_clf_joblib.pkl
  Python/machine-learning-news-scrapper/models/pac.pkl
  Python/machine-learning-news-scrapper/models/tfv.pkl
  Python/machine-learning-news-scrapper/models/tfv_vec.pkl
  Python/machine-learning-news-scrapper/requirements.txt
Labels: PR:Ready-to-Review

#1200 Randomyt
  Python/Random_Youtube_Videos/.env_sample
  Python/Random_Youtube_Videos/README.md
  Python/Random_Youtube_Videos/randomyt.py
  Python/Random_Youtube_Videos/requirements.txt
Labels: PR:Ready-to-Review

#1186 Go hackernews Scraper
  Golang/HackerNews_Comment_Scrapper/README.md
  Golang/HackerNews_Comment_Scrapper/go.mod
  Golang/HackerNews_Comment_Scrapper/go.sum
  Golang/HackerNews_Comment_Scrapper/main.go
Labels: PR:Reviewed, PR:Ready-to-Review

#1188 CoVID-19 Cases using Web Scraping
  Python/Covid_Cases_Scraper/README.md
  Python/Covid_Cases_Scraper/covid.py
  Python/Covid_Cases_Scraper/requirements.txt
Labels: PR:Ready-to-Review
