Repository HarshCasper/Rotten-Scripts, pull requests merged in 2022-03, with the labels that each got.

#1312 Rust Email Script Added
  Rust/README.md
  Rust/email-validator/Cargo.lock
  Rust/email-validator/Cargo.toml
  Rust/email-validator/README.md
  Rust/email-validator/src/main.rs
Labels: GSSOC22

#1300 Added Intagram BOT #1296
  Python/Instagram_BOT/README.md
  Python/Instagram_BOT/instagram_bot.py
  Python/Instagram_BOT/requirements.txt
Labels: PR:Reviewed, PR:Ready-to-Review

#1329 (Bug fix): Twitter Unfollowers API Node script wasn't working as expected.
  JavaScript/Twitter_Unfollowers/Twitter_Unfollowers.js
Labels: PR:Ready-to-Review
